name: Mergesort
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Run Mergesort
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python sort/mergesort.py

